# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# - task: DotNetCoreCLI@2
#   inputs:
#     command: build
#     configuration: $(buildConfiguration)
#     projects: 

- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: backend/QandA/QandA
  displayName: 'backend build'

- script: dotnet test
  workingDirectory: backend/QandA/BackEndTests
  displayName: 'backend tests'

- script: dotnet publish --configuration $(buildConfiguration)
  workingDirectory: backend/QandA/QandA
  displayName: 'backend publish'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'backend/QandA/QandA/bin/Release/netcoreapp3.1/publish'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/backend/QandA/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'backend zip files'  

- task: PublishBuildArtifacts@1
  inputs: 
    pathToPublish: '$(Build.ArtifactStagingDirectory)/backend/QandA'
    artifactName: 'backend'
  displayName: 'backend publish to pipeline'

- script: yarn
  workingDirectory: frontend
  displayName: 'frontend install dependencies'

- script: yarn run test:ci
  workingDirectory: frontend
  displayName: 'frontend tests'

- script: yarn run build:staging
  workingDirectory: frontend
  displayName: 'frontend staging build'

- task: ArchiveFiles@2
  inputs: 
   rootFolderOrFile: 'frontend/build'
   includeRootFolder: false
   archiveType: zip
   archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-staging/build.zip'
   replaceExistingArchive: true
  displayName: 'frontend staging zip files'

- task: ArchiveFiles@2
  inputs: 
   rootFolderOrFile: 'frontend/cypress'
   includeRootFolder: false
   archiveType: zip
   archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-staging/tests.zip'
   replaceExistingArchive: true
  displayName: 'frontend cypress zip files'

- task: PublishBuildArtifacts@1
  inputs: 
    pathToPublish: '$(Build.ArtifactStagingDirectory)/frontend-staging'
    artifactName: 'frontend-staging'
  displayName: 'frontend staging publish to pipeline'

- script: yarn run build:production
  workingDirectory: frontend
  displayName: 'frontend production build'

- task: ArchiveFiles@2
  inputs: 
    rootFolderOrFile: 'frontend/build'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-production/build.zip'
    replaceExistingArchive: true
  displayName: 'frontend production zip files'

- task: PublishBuildArtifacts@1
  inputs: 
    pathToPublish: '$(Build.ArtifactStagingDirectory)/frontend-production'
    artifactName: 'frontend-production'
  displayName: 'frontend production publish to pipeline'
